CREATE TABLE Customers (
    customer_id int NOT NULL PRIMARY KEY,
    customer_code varchar(255) UNIQUE,
    contact_name varchar(255),
    active TINYINT DEFAULT 1
);

INSERT INTO TABLE_NAME VALUES (VALUE1, VALUE2, …);
INSERT INTO CUSTOMERS VALUES(1, 'A1','MAEGAN', 1);
INSERT INTO CUSTOMERS VALUES(2, 'A2','DENNIS', 0);

INSERT INTO TABLE_NAME
	(COLUMN_1, COLUMN_2, …) 
VALUES 
	(VALUE1, VALUE2, …);

INSERT INTO CUSTOMERS 
	(CUSTOMER_ID, CUSTOMER_CODE, CONTACT_NAME) 
VALUES 
	(3, 'A3','LANA');

SELECT * FROM TABLE_NAME;
SELECT * FROM CUSTOMERS;
